import uuid
from app.services.github_service import GithubService

class PRAgent:

    @staticmethod
    def create_pr_for_fixes(
        repository_path: str,
        repository_url: str,
        fixes: list,
        branch_name: str | None = None
    ):
        if not fixes:
            print("No fixes to create a Pull Request for.")
            return None

        if not branch_name:
            branch_name = f"bugbountyhunter/patch-{uuid.uuid4().hex[:8]}"

        # 1. Create a git branch and switch to it
        GithubService.create_branch(repository_path, branch_name)

        # 2. Stage changes and commit them
        commit_message = "style/security: automated fixes by BugBountyHunter\n\nResolved the following issues:\n"
        for fix in fixes:
            commit_message += f"- Fixed issue in {fix.get('file_path')}\n"

        GithubService.commit_changes(repository_path, commit_message)

        # 3. Push the branch to remote
        pushed = GithubService.push_branch(repository_path, branch_name)
        if not pushed:
            print(f"Failed to push branch {branch_name} to remote. PR will not be created.")
            return None

        # 4. Create the PR using GitHub API
        pr_title = "BugBountyHunter: Automated code repairs applied"
        pr_body = (
            "This is an automated pull request containing fixes generated by BugBountyHunter.\n\n"
            "### Summary of Changes:\n"
        )
        for fix in fixes:
            pr_body += f"- **File**: `{fix.get('file_path')}`\n"
            if fix.get("patch"):
                pr_body += f"  <details><summary>Unified Diff Patch</summary>\n\n```diff\n{fix.get('patch')}\n```\n\n</details>\n"
            pr_body += "\n"

        pr_info = GithubService.create_pull_request(
            repo_url=repository_url,
            branch_name=branch_name,
            title=pr_title,
            body=pr_body
        )

        if pr_info:
            print(f"Pull Request created successfully: {pr_info.get('html_url')}")
            return pr_info
        else:
            print("Failed to create Pull Request on GitHub.")
            return None
